export const IPC = {
  chatGet: 'chat:get',
  chatNew: 'chat:new',
  chatSelect: 'chat:select',
  chatAttach: 'chat:attach',
  chatSend: 'chat:send',
  chatCancel: 'chat:cancel',
  chatUpdate: 'chat:update',
  agentSettingsGet: 'agent-settings:get',
  agentSettingsSave: 'agent-settings:save',
  agentConnectionTest: 'agent-settings:test',
  sourcesList: 'sources:list',
  monitorStart: 'monitor:start',
  demoStart: 'demo:start',
  monitorStop: 'monitor:stop',
  detectorAnalyze: 'detector:analyze',
  detectorMode: 'detector:mode',
  detectorHealth: 'detector:health',
  mediaAnalyze: 'media:analyze',
  mediaCancel: 'media:cancel',
  stateGet: 'state:get',
  stateUpdate: 'state:update',
  overlayDetails: 'overlay:details',
  overlayExpand: 'overlay:expand'
} as const
